### ISSUE TITLE
XDMOD for NERC Data says Mass Open Cloud

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/xdmod-cntr#103]
See screenshot.  Should be changed before offered to users.![xdmod.png](https://images.zenhubusercontent.com/62b0bcb4ba912dbb31713c09/8e83c365-91de-49e4-89f2-255c3bc03959)

**Comment by rob-baron** [comment]
@msdisme - That is actually working as expected.  What you have brought up is the summary for the HPC part.

Here is what I see when I choose the cloud summary:

![image](https://user-images.githubusercontent.com/23174942/207378213-065744eb-b5c4-4d72-a2d2-27f99e37206a.png)

And I can select a subsection:

![image](https://user-images.githubusercontent.com/23174942/207378805-158ff70d-00d1-46e5-8f43-5a9c1ed233f5.png)

of course the there is no utilization data as I don't have the hypervisor job running yet (coming soon!).

**Comment by msdisme** [comment]
Sorry I was  so unclear.  It’s the text in the description at the bottom which I thought needed updating.

**Comment by rob-baron** [comment]
I'll change the organization name
