### ISSUE TITLE
Seem to be hitting a Kubernetes kustomization bug that was fixed

### ISSUE THREAD

**Issue by rob-baron** [CCI-MOC/xdmod-cntr#110]
I seem to be hitting this (https://github.com/kubernetes-sigs/kustomize/issues/4062) when I am trying to patch a kubernetes cron job, with the following error:

```
oc apply -k k8s/overlays/nerc-ocp-infra
error: no matches for Id CronJob.[noVer].[noGrp]/cj-xdmod-openstack.[noNs]; failed to find unique target for patch CronJob.[noVer].[noGrp]/cj-xdmod-openstack.[noNs]
```

**Comment by larsks** [comment]
@rob-baron what version of `oc` are you running?

**Comment by rob-baron** [comment]
oc version
Client Version: 4.12.0-202208031327
Kustomize Version: v4.5.4
Server Version: 4.10.15
Kubernetes Version: v1.23.5+3afdacb

**Comment by larsks** [comment]
@rob-baron I'm not able to reproduce this behavior. Where are you trying to patch a CronJob in the current configuration? I see a patch in `k8s/overlays/nerc-ocp-infra/patches/cj-xdmod-openstack-shred.yaml`, but this doesn't seem to be referenced anywhere in the configuration.

`k8s/overlays/nerc-ocp-infra/kustomization.yaml` only includes resources; it doesn't have any patch configuration.

**Comment by rob-baron** [comment]
@larsks, because I was getting the error, I was reluctant to reference that file as it would potentially have the same issue when being deployed on the nerc.  I included the file anyways as I created this issue as this is how I would want to deploy it.

So am I using the correct version of kustomize?

**Comment by larsks** [comment]
@rob-baron, Can you update this issue with an example of how you're referencing the patch?

**Comment by rob-baron** [comment]
@larsks, Since you are trying to reproduce it, I am assuming you mean to say that I am using the correct version of kustiomization that has the fix for this issue.  I'll let you know if I succeed at replicating this.

**Comment by larsks** [comment]
@rob-baron I'm not really saying anything of the sort.

I'm asking, since you've opened this issue, that you include enough information to reproduce the problem you're asking about. Without that it's a guessing game, so I haven't invested too much time yet.

**Comment by rob-baron** [comment]
@larsks Let me start again as I fear that we are talking past each other.

```
    1) Initially, I opened this issue mainly as a place holder of something that I had to work a round.  Did feel that I needed to include all of the information to replicate it when I was opening it as I worked around it.  I also didn't want to invest more time in the definition as it could have been a trivial problem to solve.

    2) I included the patch file as I spent time eyeballing it and I think it is either correct or close to correct

    3) I didn't include it in the nerc kustomization file as it might break the install on the nerc

    4) I assumed that since you stated you could not reproduce this, that you had tried to reproduce this

    5) When I stated that I am working on replicating this and will inform you that means one of the following:

    5.1) I am unable to replicated this and have submitted a PR that will close this issue

    5.2) I am able to replicated this and have instructions to do so within this ticket.
```

Since later is now, I am working on it in a manner that I can test it on ocp-staging and on the nerc-ocp-infra so that I don't disturb what is currently working in both places.  Once I have done this, I will be able to use the nerc-ocp-infra cluster for both staging and production, though this might require a bit of reorganization.  This requires a bit of work as I don't want to undo the work that both mainn and I did in the xdmod project.

Also based on the explanation of the bug that was fixed, I am suspecting that I may see it on ocp-staging, but not on nerc-ocp-infra.  It is just a suspicion, so I will be working on confirming this.

You can let me know if I am not using GitHub issues correctly in that we should provide all information to reproduce an issue within the issue at the time of writing, as opposed to just quickly creating the issue as something that requires a bit more work.

**Comment by rob-baron** [comment]
Wasn't hitting the kubernetes bug.  I misspelled the apiVersion, and it works in both ocp-staging and in nerc-ocp-infra.
