### ISSUE TITLE
Google Chrome is proprietary software, vs Chromium

### ISSUE THREAD

**Issue by knikolla** [CCI-MOC/xdmod-cntr#127]
XDMoD requires Chromium in their [software requirements](https://open.xdmod.org/10.0/software-requirements.html) and recommends the `chromium-headless` package.

In the Dockerfiles, we're installing both Google Chrome and Chromium headless. 

While Chromium is open source software, Google Chrome is not, and we wouldn't be able to distribute the current XDMod container if we were to publish it in a public repository.

https://github.com/CCI-MOC/xdmod-cntr/blob/45f5b509609e288a422de58859e77ba695e26030/Dockerfile.moc-xdmod#L4

https://github.com/CCI-MOC/xdmod-cntr/blob/45f5b509609e288a422de58859e77ba695e26030/Dockerfile.moc-xdmod#L13

We should investigate whether `chromium-headless` works fine and if we can safely remove the installation and repo for Google Chrome.

**Comment by knikolla** [comment]
This provides some background. https://github.com/ubccr/xdmod/pull/1452

> so there is no way at the moment that we can easily manage using chromium for our CI tests. The version of chromium is a moving target, but the test harness has some hardcoded stuff in it to require a specific version of the chromedriver. The version of chromium that ships with EPEL is no longer compatible with the version that we hardcode

So apparently they're having trouble keeping their testing stable (specifically UI tests) using Chromium instead of Google Chrome. But since we're not running their tests we should be all clear to remove Chrome.

**Comment by rob-baron** [comment]
I didn't really want to change the docker file from what the xdmod folks were using and I eventually want to be able to run their CI tests.  But I have already separated the docker files to a "development" version and a production version.

There should also be a test docker image that included the production docker image with their CI tests, with the development docker including the test docker image.  I'll start an issue for the test docker file.

**Comment by knikolla** [comment]
Resolved by #129
