### ISSUE TITLE
implement function(s) to handle volume events.

### ISSUE THREAD

**Issue by rob-baron** [CCI-MOC/xdmod-cntr#13]
implement function(s) to handle volume events.

**Comment by joachimweyl** [comment]
@rob-baron I know you have been doing some great work on this. In an effort to continue your focused small PRs, would it be helpful to do a pull request for what you have so far? Or maybe a combined one with this and #18 assuming that would not already be too large. If so then 2 separate PRs.

**Comment by rob-baron** [comment]
Personally, I am not sure what use this is, but my progress so far has been to:

1. Start with a top down approach to create a similar layout to the compute processing side
2. Realize that some of the compute processing side can be reused, and so refactoring that
3. started working from the bottom up in processing the volume side, refactoring the compute side needed
4. rework some of the code written in the top-down manner to fit with what the specific implementation of the bottom-up approach.

**Comment by rob-baron** [comment]
The functions are there to handle volume events.
