### ISSUE TITLE
XDMoD display of OpenShift information may not use legible names

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/xdmod-cntr#139]
There is currently OpenShift data in XDMoD for Milson's test project. The XDMoD UI for this project shows the following:

* a PI report labels him as '2'
*  a user report labels him as '593ee1d6c7fa442f8a33c1e3942bb73d'

These are his cf_project_id and his OpenShift project name respectively. I don't know if these labels are appropriate - if these are test-type values - or if ColdFront will always generate projects with similar values. If the latter, it's possible we want to rearrange our generated XDMoD log file to assign more readable labels.

**Comment by joachimweyl** [comment]
@tzumainn is this solved by this [issue](https://github.com/nerc-project/coldfront-plugin-cloud/pull/88)?

**Comment by tzumainn** [comment]
Ah, yep! I'll close this.
