### ISSUE TITLE
Create a working set of hierarchy files.

### ISSUE THREAD

**Issue by rob-baron** [CCI-MOC/xdmod-cntr#144]
Build a set of hierarchy files based on the data that we currently have from the nerc.

**Comment by joachimweyl** [comment]
@rob-baron can you give us an update on status and steps taken to arrive at current status.

**Comment by rob-baron** [comment]
![Screenshot 2023-02-16 at 3 31 53 PM](https://user-images.githubusercontent.com/23174942/219481203-276b2c0b-cecc-4e29-9e03-ebb84a6c0a79.png)

PI to project demonstrated.

**Comment by rob-baron** [comment]
To summarize:

For cloud resources (openstack):
1) have been able to associate PIs to Projects
2) Have NOT been able to associate Projects with either groups or the hierarchy - have a query into xdmod about that.
3) Have a couple of things to try in the meanwhile

For HPC resources (openshift):
1) have been able to associate groups to projects (in the HPC view PI and group are synonyms).

The main implication is that the hierarchy as defined should probably be adjusted. The current hierarchy is as follows
1) Institution (ie, BU, HU, NEU ... ) 2) School/Center/intitute (FAS, CFA, CAS ... ) 3) Research Discipline
With groups, identifying the PI in the groups.csv

   can adjust name of group using names.csv
We could adjust the heiarachy to keep all relevant information - perhaps:

  ```
  1) institution - school (ie BU-CAS, HU-FAS ... )
  2) PI
  3) Research Discipline
  
  using groups/projects to track the specific grant
  ```
This will fit both HPC and cloud for the current version of xdmod. Further more this fits my model of:

institutions having multiple PIs,
PIs having 1 or more Research Disciplines
PIs applying for multiple research grants
I expect these things will change as the current mechanisms in xdmod are not the most convent to work with.

**Comment by rob-baron** [comment]
Got the hierarchy working with cloud - editing the above comment.
