### ISSUE TITLE
Need to confirm the hierarchy

### ISSUE THREAD

**Issue by rob-baron** [CCI-MOC/xdmod-cntr#147]
The current hierarchy (for both HPC (OpenShift) and Cloud (OpenStack) resources):
```
1) Institution
2) Department/center
3) research area
4) PI (group is use synonymously)
5) Project (only for Cloud resources)
```

Questions:
```
1) does this provide all of the information that needs to be passed through xdmod?
2) should 3 be PI and research area
3) what is the initial format for the report that is to be generated.
```

**Comment by joachimweyl** [comment]
@rob-baron is this the current hierarchy for OpenStack, OpenShift, or both?

**Comment by rob-baron** [comment]
@joachimweyl

This is for both.

**Comment by rob-baron** [comment]
New hierarchy:

1) Institution
2) field of science
3) PI
4) project

Basic report

-    Link Institution to PI to project
    
Added bonus

-    A "transaction log" that links users with which resources they added to a particular project.
