### ISSUE TITLE
Get the hierarchy data from ColdFront into XDMoD

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/xdmod-cntr#156]
ColdFront is where we will be pulling the PI and Project information for XDMoD.

@knikolla created an [Repo](https://github.com/CCI-MOC/coldfront-plugin-api) to provide access to this information.

This issue is to ensure we pull the PI and Project information through the HTTP Endpoint.

**Comment by joachimweyl** [comment]
@knikolla will send data to @rob-baron with pgp to ensure it is secture.

**Comment by joachimweyl** [comment]
@rob-baron now that infra is working and that you have the manually created client to access keycloak/coldfront what are the next steps on this issue?

**Comment by rob-baron** [comment]
I will start on this once I get the keystone connection working.  The next steps will be:

1) figure out the correct REST call to use to connect to cold front (or kristi will give me the call that he was using)
2) confirm the data coming from cold-front matches what I am expecting

**Comment by rob-baron** [comment]
no longer blocked as we are now able to access coldfront from the infra cluster.

**Comment by joachimweyl** [comment]
@rob-baron it looks like the work for this is done. The processing of the Coldfront data will be done in [this](https://github.com/CCI-MOC/xdmod-cntr/issues/116) issue. Is that correct?

**Comment by joachimweyl** [comment]
PR merged and this issue is closed.
