### ISSUE TITLE
add kubernetes manifests for the hierarchy cron job

### ISSUE THREAD

**Issue by rob-baron** [CCI-MOC/xdmod-cntr#158]
1) should create a new pvc
2) create the cj yaml (similar to cj-xdmod-openstack-shred.yaml)
    a - run the process_hierarchy in an init container (xdmod-openstack using the command process_hierarchy.py)
    b - run the following in the container (moc-xdmod)

        xdmod-import-csv -t hierarchy -i hierarchy.csv
        xdmod-import-csv -t group-to-hierarchy -i group.csv
        xdmod-import-csv -t names -i names.csv 
        xdmod-import-csv -t cloud-project-to-pi -i pi2cloudproject.csv

**Comment by joachimweyl** [comment]
@rob-baron what are the next steps on this issue?

**Comment by rob-baron** [comment]
Addressed in (https://github.com/CCI-MOC/xdmod-cntr/pull/157)
