### ISSUE TITLE
implement get_keycloak_meta_data

### ISSUE THREAD

**Issue by rob-baron** [CCI-MOC/xdmod-cntr#160]
I don't know the exact format of this data as I don't have any examples of it, however it needs to link  the following 3 pieces:

    1) institution
    2) field of science (the PI's field of science)
    3) pi

**Comment by joachimweyl** [comment]
@knikolla what are the next steps for this issue?

**Comment by joachimweyl** [comment]
@knikolla as the Keycloak client is now created what are the next steps for this issue?

**Comment by rob-baron** [comment]
@joachimweyl - this might as well be assigned to me as I am working on integrating kristi's example into the hierarchy job.  Just plugging in the credentials that I pulled from vault returned an 'HTTP 401 Unauthorized' error instead of returning the expected data.  I am working on debugging further and expect to have something actionable by monday.

**Comment by rob-baron** [comment]
@jochimweyl, I have run kristi's code that he used with the reg-app credentials, using the newly created xdmod credentials and I still get the 'HTTP 401 Unauthorized' error.

**Comment by joachimweyl** [comment]
@knikolla @jtriley & @culbert what are your thoughts on the 401 error @rob-baron is getting when he attempts to use the new XDMoD client on Keycloak?

**Comment by joachimweyl** [comment]
@knikolla Now that the `ocp-infra` cluster can reach ColdFront and keycloak and the implementation of the retrieval of the keycloak metadata is done is this issue resolved?
