### ISSUE TITLE
Eliminate the xdmod-init-2 container from the deployment

### ISSUE THREAD

**Issue by rob-baron** [CCI-MOC/xdmod-cntr#162]
Given this issue, and that xdmod was already initialized, we can try eliminating the xdmod-init container from the init containers in the xdmod deployments.  This should work-a-round this issue (https://github.com/CCI-MOC/xdmod-cntr/issues/161).

**Comment by knikolla** [comment]
Closed by https://github.com/CCI-MOC/xdmod-cntr/pull/164
