### ISSUE TITLE
Aggregation stoping due to a constraint

### ISSUE THREAD

**Issue by rob-baron** [CCI-MOC/xdmod-cntr#167]
The following message is coming from xdmod-ingestor:

2023-04-29 13:46:19 [critical] Aggregation failed: xdmod.cloud-state-pipeline.cloud-session-records (ETL\Ingestor\DatabaseIngestor): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'processorbucket_id' cannot be null Exception: 'SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'processorbucket_id' cannot be null' 

(stacktrace: 

#0 /usr/share/xdmod/classes/ETL/Ingestor/pdoIngestor.php(544): CCR\Loggable->logAndThrowException('SQLSTATE[23000]...', Array)

#1 /usr/share/xdmod/classes/ETL/Ingestor/pdoIngestor.php(459): ETL\Ingestor\pdoIngestor->singleDatabaseIngest()

#2 /usr/share/xdmod/classes/ETL/Ingestor/aIngestor.php(126): ETL\Ingestor\pdoIngestor->_execute()

#3 /usr/share/xdmod/classes/ETL/EtlOverseer.php(473): ETL\Ingestor\aIngestor->execute(Object(ETL\EtlOverseerOptions))

#4 /usr/share/xdmod/classes/ETL/EtlOverseer.php(435): ETL\EtlOverseer->_execute('xdmod.cloud-sta...', Object(ETL\Ingestor\DatabaseIngestor))

#5 /usr/share/xdmod/classes/ETL/Utilities.php(281): ETL\EtlOverseer->execute(Object(ETL\Configuration\EtlConfiguration))

#6 /usr/share/xdmod/classes/OpenXdmod/DataWarehouseInitializer.php(362): ETL\Utilities::runEtlPipeline(Array, Object(CCR\Logger), Array)

#7 /usr/bin/xdmod-ingestor(310): OpenXdmod\DataWarehouseInitializer->aggregateCloudData('2018-01-01 12:3...')

#8 /usr/bin/xdmod-ingestor(21): main()

#9 {main})

**Comment by rob-baron** [comment]
This constraint is triggered when a VM has the number of processors outside of the ranges in the mode_cloud.processor_buckets table.

```
MariaDB [(none)]> SELECT * FROM modw_cloud.processor_buckets
    -> ;
+----+----------------+----------------+-------------+
| id | min_processors | max_processors | description |
+----+----------------+----------------+-------------+
|  1 |              1 |              1 | 1           |
|  2 |              2 |              3 | 2 - 3       |
|  3 |              4 |              7 | 4 - 7       |
|  4 |              8 |             11 | 8 - 11      |
|  5 |             12 |             15 | 12 - 15     |
|  6 |             16 |             32 | 16 - 32     |
|  7 |             33 |     2147483647 | > 32        |
+----+----------------+----------------+-------------+
7 rows in set (0.01 sec)
```

Not sure what data is out of range.

**Comment by rob-baron** [comment]
The xdmod team gave me a couple of queries to run.

This is due to some unknown flavors:
```
SELECT * FROM modw_cloud.instance_type WHERE num_cores < 1 AND resource_id != -1
    -> ;
+-------------+------------------+------------------------------------------------------+------------------------------------------------------+-------------+-----------+-----------+---------+-------------------+----------+
| resource_id | instance_type_id | instance_type                                        | display                                              | description | num_cores | memory_mb | disk_gb | start_time        | end_time |
+-------------+------------------+------------------------------------------------------+------------------------------------------------------+-------------+-----------+-----------+---------+-------------------+----------+
|           2 |               13 | unknown flavor(0cdf836c-e0a6-48ba-b98d-e8ed7e313acf) | unknown flavor(0cdf836c-e0a6-48ba-b98d-e8ed7e313acf) | NULL        |         0 |         0 |       0 | 1644361873.000000 |     NULL |
|           2 |               14 | unknown flavor(1202a547-f2d7-4f8c-bb2b-e55bcce24f0f) | unknown flavor(1202a547-f2d7-4f8c-bb2b-e55bcce24f0f) | NULL        |         0 |         0 |       0 | 1648474547.000000 |     NULL |
|           2 |               15 | unknown flavor(255ae564-1164-43eb-b3da-13a115f4c722) | unknown flavor(255ae564-1164-43eb-b3da-13a115f4c722) | NULL        |         0 |         0 |       0 | 1644526590.000000 |     NULL |
|           2 |               16 | unknown flavor(3dfd915f-4730-434f-aec9-f1fb738423fd) | unknown flavor(3dfd915f-4730-434f-aec9-f1fb738423fd) | NULL        |         0 |         0 |       0 | 1646354299.000000 |     NULL |
|           2 |               17 | unknown flavor(8dcbf98b-412c-44b7-a56a-cb8dbec11d4b) | unknown flavor(8dcbf98b-412c-44b7-a56a-cb8dbec11d4b) | NULL        |         0 |         0 |       0 | 1647996018.000000 |     NULL |
|           2 |               18 | unknown flavor(d3652ccd-713e-40a0-83b6-78888bf10015) | unknown flavor(d3652ccd-713e-40a0-83b6-78888bf10015) | NULL        |         0 |         0 |       0 | 1647960881.000000 |     NULL |
|           2 |               19 | unknown flavor(e2ec72ca-d9a7-4be8-991b-6c94e109ff95) | unknown flavor(e2ec72ca-d9a7-4be8-991b-6c94e109ff95) | NULL        |         0 |         0 |       0 | 1644361910.000000 |     NULL |
|           2 |               20 | unknown flavor(f8a78508-9dc5-4374-8f12-4b3ea0037991) | unknown flavor(f8a78508-9dc5-4374-8f12-4b3ea0037991) | NULL        |         0 |         0 |       0 | 1646836326.000000 |     NULL |
+-------------+------------------+------------------------------------------------------+------------------------------------------------------+-------------+-----------+-----------+---------+-------------------+----------+
8 rows in set (0.00 sec)
```

And VMs:

use modw_cloud
SELECT 
    ->     i.provider_identifier,
    ->     itt.display
    -> FROM 
    ->     event AS ev
    -> JOIN
    ->     instance AS i ON ev.instance_id = i.instance_id
    -> JOIN
    ->     instance_data AS itd ON itd.resource_id = ev.resource_id AND itd.event_id = ev.event_id
    -> JOIN
    ->     instance_type AS itt ON itt.instance_type_id = itd.instance_type_id
    -> WHERE
    ->     ev.event_type_id IN (1,7,57,56,58,60,63,2,8,16,20,61,59,4,3,5,44,54,62,64,6,17,19,45,55)
    -> AND
    ->     itt.num_cores < 1
    -> GROUP BY
    ->     1
    -> ORDER BY 
    ->     2 DESC;
+--------------------------------------+------------------------------------------------------+
| provider_identifier                  | display                                              |
+--------------------------------------+------------------------------------------------------+
| 3b49b4a1-e599-47da-9663-24d4d63161bb | unknown flavor(f8a78508-9dc5-4374-8f12-4b3ea0037991) |
| bec5eee6-41ed-4a45-8e5b-03cdeeca522c | unknown flavor(f8a78508-9dc5-4374-8f12-4b3ea0037991) |
| 316cfc5a-8ce7-40a3-ab77-dc195ee27f99 | unknown flavor(e2ec72ca-d9a7-4be8-991b-6c94e109ff95) |
| 3c6e0762-1684-485d-af2b-1ce661756c0e | unknown flavor(e2ec72ca-d9a7-4be8-991b-6c94e109ff95) |
| 43d1a789-8f02-4f38-a7dd-aa5a22471df9 | unknown flavor(e2ec72ca-d9a7-4be8-991b-6c94e109ff95) |
| 4709691f-fbbe-4c9b-b5dd-abf08a902ed5 | unknown flavor(e2ec72ca-d9a7-4be8-991b-6c94e109ff95) |
| 49dce22b-9d37-41cd-ab4a-4281d992405f | unknown flavor(e2ec72ca-d9a7-4be8-991b-6c94e109ff95) |
| bb6714ae-0ff1-46c7-91b7-54d710e47a03 | unknown flavor(e2ec72ca-d9a7-4be8-991b-6c94e109ff95) |
| d6a23df1-7a66-4ac6-bee9-dcc8cb7ecfa5 | unknown flavor(e2ec72ca-d9a7-4be8-991b-6c94e109ff95) |
| 7e4ab562-26b7-4752-839d-8fa2cef5b15a | unknown flavor(e2ec72ca-d9a7-4be8-991b-6c94e109ff95) |
| 35d3ff99-6049-4949-b80a-4e6e1366b667 | unknown flavor(d3652ccd-713e-40a0-83b6-78888bf10015) |
| bf909c93-d6ab-482e-96ff-5578cfedf561 | unknown flavor(d3652ccd-713e-40a0-83b6-78888bf10015) |
| c05e721a-a6a8-459d-b169-63f402d78450 | unknown flavor(8dcbf98b-412c-44b7-a56a-cb8dbec11d4b) |
| 6e3621f1-9906-4c24-9b4c-77a6e36d3952 | unknown flavor(3dfd915f-4730-434f-aec9-f1fb738423fd) |
| 704eda7b-5f37-4faa-ad41-f6778039c716 | unknown flavor(3dfd915f-4730-434f-aec9-f1fb738423fd) |
| ebd97abd-2ea0-434f-be6c-a35115d1b890 | unknown flavor(3dfd915f-4730-434f-aec9-f1fb738423fd) |
| db6232cb-f7be-4ecd-b9ee-b2ba96b1ec0c | unknown flavor(255ae564-1164-43eb-b3da-13a115f4c722) |
| 68e62958-94b3-4e6c-890b-2d40255e2788 | unknown flavor(255ae564-1164-43eb-b3da-13a115f4c722) |
| 7da31851-a76b-44a1-9655-c7d22374b635 | unknown flavor(255ae564-1164-43eb-b3da-13a115f4c722) |
| 8863a1da-cce6-419d-b100-0aa3a90d6877 | unknown flavor(255ae564-1164-43eb-b3da-13a115f4c722) |
| b3fdb40c-58fd-4759-bc57-51b123bb312d | unknown flavor(255ae564-1164-43eb-b3da-13a115f4c722) |
| c6479b16-fab2-413d-8e70-aa4b06b2e865 | unknown flavor(255ae564-1164-43eb-b3da-13a115f4c722) |
| 030db1c8-5a0f-4645-891f-8abb7ea56505 | unknown flavor(1202a547-f2d7-4f8c-bb2b-e55bcce24f0f) |
| 11c3f55f-e095-401e-b344-c6c96bdb370f | unknown flavor(1202a547-f2d7-4f8c-bb2b-e55bcce24f0f) |
| 165308f1-2b15-4bd7-b707-a805bb760fba | unknown flavor(1202a547-f2d7-4f8c-bb2b-e55bcce24f0f) |
| 24a2588c-fdd0-4c3a-9cde-fd85f48a5219 | unknown flavor(1202a547-f2d7-4f8c-bb2b-e55bcce24f0f) |
| 827d7ce6-0fec-4527-bc50-a410131204f1 | unknown flavor(1202a547-f2d7-4f8c-bb2b-e55bcce24f0f) |
| bc54dc70-dae3-40f6-bd24-7d7a8826e570 | unknown flavor(1202a547-f2d7-4f8c-bb2b-e55bcce24f0f) |
| d38313b2-77fd-4965-8cb6-9b5a70e840a6 | unknown flavor(1202a547-f2d7-4f8c-bb2b-e55bcce24f0f) |
| 8affc9ff-c1b2-48bd-b09c-c39eccc67ae8 | unknown flavor(0cdf836c-e0a6-48ba-b98d-e8ed7e313acf) |
| 8b37b019-7295-43ca-82bc-ac15e0a9164e | unknown flavor(0cdf836c-e0a6-48ba-b98d-e8ed7e313acf) |
| 981ce43e-a9d4-4701-9299-60471af44de6 | unknown flavor(0cdf836c-e0a6-48ba-b98d-e8ed7e313acf) |
+--------------------------------------+------------------------------------------------------+
32 rows in set (4.42 sec)

**Comment by rob-baron** [comment]
here is the sql to run to fix the aggregation error:

use modw_cloud

select * from instance_type where instance_type like "unknown flavor%";

```
+-------------+------------------+------------------------------------------------------+------------------------------------------------------+-------------+-----------+-----------+---------+-------------------+----------+
| resource_id | instance_type_id | instance_type                                        | display                                              | description | num_cores | memory_mb | disk_gb | start_time        | end_time |
+-------------+------------------+------------------------------------------------------+------------------------------------------------------+-------------+-----------+-----------+---------+-------------------+----------+
|           2 |               13 | unknown flavor(0cdf836c-e0a6-48ba-b98d-e8ed7e313acf) | unknown flavor(0cdf836c-e0a6-48ba-b98d-e8ed7e313acf) | NULL        |         0 |         0 |       0 | 1644361873.000000 |     NULL |
|           2 |               14 | unknown flavor(1202a547-f2d7-4f8c-bb2b-e55bcce24f0f) | unknown flavor(1202a547-f2d7-4f8c-bb2b-e55bcce24f0f) | NULL        |         0 |         0 |       0 | 1649795786.000000 |     NULL |
|           2 |               15 | unknown flavor(255ae564-1164-43eb-b3da-13a115f4c722) | unknown flavor(255ae564-1164-43eb-b3da-13a115f4c722) | NULL        |         0 |         0 |       0 | 1644526590.000000 |     NULL |
|           2 |               16 | unknown flavor(3dfd915f-4730-434f-aec9-f1fb738423fd) | unknown flavor(3dfd915f-4730-434f-aec9-f1fb738423fd) | NULL        |         0 |         0 |       0 | 1646354299.000000 |     NULL |
|           2 |               17 | unknown flavor(8dcbf98b-412c-44b7-a56a-cb8dbec11d4b) | unknown flavor(8dcbf98b-412c-44b7-a56a-cb8dbec11d4b) | NULL        |         0 |         0 |       0 | 1647996018.000000 |     NULL |
|           2 |               18 | unknown flavor(d3652ccd-713e-40a0-83b6-78888bf10015) | unknown flavor(d3652ccd-713e-40a0-83b6-78888bf10015) | NULL        |         0 |         0 |       0 | 1647960881.000000 |     NULL |
|           2 |               19 | unknown flavor(e2ec72ca-d9a7-4be8-991b-6c94e109ff95) | unknown flavor(e2ec72ca-d9a7-4be8-991b-6c94e109ff95) | NULL        |         0 |         0 |       0 | 1644361910.000000 |     NULL |
|           2 |               20 | unknown flavor(f8a78508-9dc5-4374-8f12-4b3ea0037991) | unknown flavor(f8a78508-9dc5-4374-8f12-4b3ea0037991) | NULL        |         0 |         0 |       0 | 1646836326.000000 |     NULL |
+-------------+------------------+------------------------------------------------------+------------------------------------------------------+-------------+-----------+-----------+---------+-------------------+----------+
8 rows in set (0.03 sec)
```

update instance_type set num_cores=1, memory_mb=1, disk_gb=1 where instance_type in
  ("unknown flavor(f8a78508-9dc5-4374-8f12-4b3ea0037991)",
   "unknown flavor(e2ec72ca-d9a7-4be8-991b-6c94e109ff95)",
    "unknown flavor(d3652ccd-713e-40a0-83b6-78888bf10015)",
    "unknown flavor(8dcbf98b-412c-44b7-a56a-cb8dbec11d4b)",
    "unknown flavor(3dfd915f-4730-434f-aec9-f1fb738423fd)",
    "unknown flavor(255ae564-1164-43eb-b3da-13a115f4c722)",
    "unknown flavor(1202a547-f2d7-4f8c-bb2b-e55bcce24f0f)",
    "unknown flavor(0cdf836c-e0a6-48ba-b98d-e8ed7e313acf)");
    
----

**Comment by rob-baron** [comment]
The sql give the unknown flavors a value of 1 for each of the possible aggregations.

We will know that there is an unknown flavor, as that is the name that the flavor has.  Furthermore, we should be able to get an inclination when the overall field doesn't match the expected results.

**Comment by msdisme** [comment]
for this, and openstack, what monitoring is/can be done to make sure we/ops team are aware of problems in billing?

**Comment by rob-baron** [comment]
I need to come up with a more robust solution, in that I have map out the entire data flow, as the new data is being shredded and creating new entries in the table that I just updated.  

1) fix the job that is pulling data from openstack to give unknown flavors 1 vCPU.
2) resize the VMs that are using the unknown flavors

strategy 1:

follow the dataflow and update references to any table that references an unknown flavor and set it to a known flavor.
(should only have to do the shredding part, as the ingestor will probably do the rest)

strategy 2:

fix the  json input files, restored and reinvest.


So, It looks like we are running some VMs that have been running since the cluster started for administrative purposes. In any case, resizing those VMs to use a standard size, or to create standard flavors for those VMs  would be an obvious first step.  The VM ids the provider ids mentioned above and here:

```
 3b49b4a1-e599-47da-9663-24d4d63161bb 
 bec5eee6-41ed-4a45-8e5b-03cdeeca522c 
 316cfc5a-8ce7-40a3-ab77-dc195ee27f99 
 3c6e0762-1684-485d-af2b-1ce661756c0e 
 43d1a789-8f02-4f38-a7dd-aa5a22471df9 
 4709691f-fbbe-4c9b-b5dd-abf08a902ed5 
 49dce22b-9d37-41cd-ab4a-4281d992405f 
 bb6714ae-0ff1-46c7-91b7-54d710e47a03 
 d6a23df1-7a66-4ac6-bee9-dcc8cb7ecfa5 
 7e4ab562-26b7-4752-839d-8fa2cef5b15a 
 35d3ff99-6049-4949-b80a-4e6e1366b667 
 bf909c93-d6ab-482e-96ff-5578cfedf561 
 c05e721a-a6a8-459d-b169-63f402d78450 
 6e3621f1-9906-4c24-9b4c-77a6e36d3952 
 704eda7b-5f37-4faa-ad41-f6778039c716 
 ebd97abd-2ea0-434f-be6c-a35115d1b890 
 db6232cb-f7be-4ecd-b9ee-b2ba96b1ec0c 
 68e62958-94b3-4e6c-890b-2d40255e2788 
 7da31851-a76b-44a1-9655-c7d22374b635 
 8863a1da-cce6-419d-b100-0aa3a90d6877 
 b3fdb40c-58fd-4759-bc57-51b123bb312d 
 c6479b16-fab2-413d-8e70-aa4b06b2e865 
 030db1c8-5a0f-4645-891f-8abb7ea56505 
 11c3f55f-e095-401e-b344-c6c96bdb370f 
 165308f1-2b15-4bd7-b707-a805bb760fba
 24a2588c-fdd0-4c3a-9cde-fd85f48a5219 
 827d7ce6-0fec-4527-bc50-a410131204f1 
 bc54dc70-dae3-40f6-bd24-7d7a8826e570 
 d38313b2-77fd-4965-8cb6-9b5a70e840a6 
 8affc9ff-c1b2-48bd-b09c-c39eccc67ae8 
 8b37b019-7295-43ca-82bc-ac15e0a9164e 
 981ce43e-a9d4-4701-9299-60471af44de6 
```

**Comment by rob-baron** [comment]
As for monitoring, I am expect that it can be extracted as a report from xdmod as it appears as a database file which is used in the aggregation of data.

**Comment by rob-baron** [comment]
This has been fixed so that aggregation is finishing without this error.

We should fix the unknown flavors on openstack.

**Comment by rob-baron** [comment]
Have added the follow on issue (https://github.com/OCP-on-NERC/operations/issues/146) to either fix the VMs or to update the privileges of the xdmod accounted.
