### ISSUE TITLE
Use actual names instead of email addresses

### ISSUE THREAD

**Issue by rob-baron** [CCI-MOC/xdmod-cntr#174]
In our meeting on 10-MAY-2023, it was suggested that we should use the actual names of the PIs instead of their email address

This can be done as regapp adds the names to the meta data it saves with keycloak and these names can be placed into the the names.csv file.

**Comment by joachimweyl** [comment]
Awaiting draft PR to be included in a PR

**Comment by rob-baron** [comment]
addressed in (https://github.com/CCI-MOC/xdmod-cntr/pull/157)
