### ISSUE TITLE
Map volume (cinder) events based on what openstack returns to ceilometer

### ISSUE THREAD

**Issue by rob-baron** [CCI-MOC/xdmod-cntr#18]
Here are the current volume events passed to xdmod:

volume.attach.end
volume.attach.start
volume.create.end
volume.create.start
volume.delete.end
volume.delete.start
volume.detach.end
volume.detach.start

note: these 2 events will be handled by a different issue:

volume.update.end
volume.update.start

**Comment by joachimweyl** [comment]
This is required for a minimum viable product.

**Comment by joachimweyl** [comment]
@rob-baron I know you have been doing some great work on this. In an effort to continue your focused small PRs, would it be helpful to do a pull request for what you have so far? Or maybe a combined one with this and #13 assuming that would not already be too large. If so then 2 separate PRs.

**Comment by rob-baron** [comment]
@joachimweyl -
1) I expect to split off the create and delete events (and implementation) in one PR
2) Cinder (volume) doesn't track events in the same way that nova (compute) does, so the events need to be crated based on what is implied by the current state and comparing certain before.

So to expound on this notion
1. if the volume exists - create the creation event and set the generated time as the create time
2. if the volume exists and its status indicates that it was deleted, create the deletion events and set the generated time as the last updated time
3. if the volume previously existed - created the deletion event and set the generated time as the current time

4. if the volume size has changed - create the resize event and set the generated time as the last updated time
5. if the volume is in use, look up the vm that that is using the volume and create the volume attach events based on the time that nova reported the volume was attached.


So the first PR will be doing 1, 2, 3.  The second pr will be for 4 and possibly 5.  Not sure if 5 is actually needed.

**Comment by rob-baron** [comment]
@joachimweyl Yes, this PR is a start on 1,2,3 (https://github.com/CCI-MOC/xdmod-cntr/pull/58).  

This issue is to resolve the errors that cropped up when trying to process the events created (https://github.com/CCI-MOC/xdmod-cntr/issues/59).

**Comment by rob-baron** [comment]
Added a new issue to take care of the update events (https://github.com/CCI-MOC/xdmod-cntr/issues/78)
