### ISSUE TITLE
run the batch export in a container

### ISSUE THREAD

**Issue by rob-baron** [CCI-MOC/xdmod-cntr#193]
Set up the script /usr/lib64/xdmod/batch_export_manager.php to run in a container in parallel to the xdmod-ui interface.

Although this screams kubernetes cron job, it updates both the database and the file system.  Since it updates the file system, we need to run in the same pod as the xdmod-ui in order that the files are present for xdmod-ui to download to the user.

**Comment by joachimweyl** [comment]
complete.
