### ISSUE TITLE
Update the OpenStack to XDMod script to work with the current version of OpenStack

### ISSUE THREAD

**Issue by rob-baron** [CCI-MOC/xdmod-cntr#2]
The current version of this script uses celometer and panko, both of which have been deprecated and removed from OpenStack as well as an older version keystone authentication.

These scripts will need to be reworked to work with keystone v3 and the currently supported OpenStack API.

**Comment by joachimweyl** [comment]
@rob-baron is this already being handled by #12 #13 #16 #18  & later #17 #19?

**Comment by rob-baron** [comment]
Sort of, I am not mentioning glance, swift, and other services that I may not realize have an impact.

**Comment by joachimweyl** [comment]
Let's just keep it as the sub tickets and add them to the Milestones as needed. That way we are not tracking multiple medium and large items inside another item. I am going to close this issue and let the progress be processed via the sub-issues. We can add Glance, Swift, and other services as needed as their own tickets. We can use the milestone to keep track of the minimum viable piece.
