### ISSUE TITLE
XDMod Shredder fails:

### ISSUE THREAD

**Issue by rob-baron** [CCI-MOC/xdmod-cntr#21]
When I run the shredder with: xdmod-shredder -f openstack -d openstack -r Cloud
I get the following error:
`2022-04-04 15:28:43 [error] {“message”:“ETL\\DataEndpoint\\DirectoryScanner (name=Open Stack event logs, path=\/etc\/xdmod\/etl\/etl_data.d\/openstack, handler=jsonfile): Path ‘\/etc\/xdmod\/etl\/etl_data.d\/openstack’ is not a directory”}
2022-04-04 15:28:43 [critical] Failed to shred files: ETL\EtlOverseer: Error verifying data endpoints:
ETL\DataEndpoint\DirectoryScanner (name=Open Stack event logs, path=/etc/xdmod/etl/etl_data.d/openstack, handler=jsonfile): Path ‘/etc/xdmod/etl/etl_data.d/openstack’ is not a directory (stacktrace: #0 /usr/share/xdmod/classes/ETL/EtlOverseer.php(379): ETL\EtlOverseer->verifyDataEndpoints(Object(ETL\Configuration\EtlConfiguration), true)`

ticket opened with the xdmod team.

**Comment by joachimweyl** [comment]
@larsks suggested specifying a fully qualified path (`-d $PWD/openstack`) instead
Mainn suggested it might be possible `/etc/xdmod` is inside `/opt/xdmod/<stuff>`
Did either of these suggestions provide any insight?

**Comment by joachimweyl** [comment]
@rob-baron is the missing files question one we should direct at someone internal specifically or XDMod Support?

**Comment by rob-baron** [comment]
@Kim - I don't think there are any missing files.  Just confirming that the configuration actually does exist in /etc/xdmod in the RPM installation as compared to the source code installation where it is located in /opt/xdmod/<stuff>.  This also allows Mainn to compare his configuration directory to see if there are any differences.

**Comment by joachimweyl** [comment]
Is this still blocking?
