### ISSUE TITLE
unable to log into admin user in xdmod interface

### ISSUE THREAD

**Issue by rob-baron** [CCI-MOC/xdmod-cntr#22]
Created use 'admin' using the create admin account in xdmod-setup:
```
========================================================================
Create Admin User
========================================================================

Username: admin
Password: 
(confirm) Password: 
First name: rob
Last name: baron
Email address: robbaron@bu.edu

Admin user created.

Press ENTER to continue. 
```

It appears in users:
```
select * from moddb.Users;
+----+-------------+--------------------------------------------------------------+----------------------+------------+-------------+-----------+---------------------+---------------------+-----------------------+-------------------+-----------+-----------------+------------------+----------------------------------+---------------------+-----------+--------+
| id | username    | password                                                     | email_address        | first_name | middle_name | last_name | time_created        | time_last_updated   | password_last_updated | account_is_active | person_id | organization_id | field_of_science | token                            | token_expiration    | user_type | sticky |
+----+-------------+--------------------------------------------------------------+----------------------+------------+-------------+-----------+---------------------+---------------------+-----------------------+-------------------+-----------+-----------------+------------------+----------------------------------+---------------------+-----------+--------+
|  1 | Public User | NULL                                                         | public@ccr.xdmod.org | Public     |             | User      | 2022-03-31 20:01:24 | 2022-03-31 20:01:24 | 0000-00-00 00:00:00   |                 1 |        -1 |              -1 |                0 | NULL                             | 0000-00-00 00:00:00 |         2 |      0 |
|  6 | admin       | $2y$10$ov69QG3GAtHKWIIVTq7i/OQq/jzwAEkbginypTpOMtuXP0HpL5G8O | robbaron@bu.edu      | rob        |             | baron     | 2022-04-04 15:05:26 | 2022-04-04 15:05:26 | 0000-00-00 00:00:00   |                 1 |        -1 |               0 |                0 | 35nBViHZvZexN1AZ3M70yKIVYWUNPNjx | 2022-05-04 15:05:26 |         2 |      0 |
+----+-------------+--------------------------------------------------------------+----------------------+------------+-------------+-----------+---------------------+---------------------+-----------------------+-------------------+-----------+-----------------+------------------+----------------------------------+---------------------+-----------+--------+
2 rows in set (0.01 sec)
```
And Here:
```
MariaDB [moddb]> select * from user_acls;
+-------------+---------+--------+
| user_acl_id | user_id | acl_id |
+-------------+---------+--------+
|           1 |       1 |      1 |
|           3 |       6 |      2 |
|           2 |       6 |      6 |
+-------------+---------+--------+
3 rows in set (0.00 sec)
```
opened a ticket with the xdmod team

**Comment by naved001** [comment]
@rob-baron I edited the post to format it better. You can see the edits I made to see what I did.

**Comment by joachimweyl** [comment]
I understand this is still blocked but is it still blocking any work we need to do or is this only blocking admin access which we might not need? Has XDMod provided any further update on this?

**Comment by joachimweyl** [comment]
@rob-baron I believe XDMod responded. Something about needing HTTPS to utilize Admin. Can you put any extra details they provided into this issue.

**Comment by rob-baron** [comment]
In lieu of bringing in the entire conversation, here is where the ticket left off:

------

Hi Robert,

It appears that the lack of ssl/https is causing this issue.  I'm not sure if there is a way around this without altering the code, but I'll bring it up with our team next week.

Jeff

 


Jeffrey T. Palmer
Scientific Programmer
Center for Computational Research
701 Ellicott Street
Buffalo, NY 14203
716 881 7567
jtpalmer@buffalo.edu
buffalo.edu/ccr

-----

I have sent a reply back on the ticket (as it was closed after this message) to see if there were any suggestions from the xdmod team.

I will start working on this after I get the data from openstack in to xdmod.  I suspect that getting the login working without ssl will be a fairly minor change - perhaps even one that can be pushed upstream.

**Comment by rob-baron** [comment]
Got the patch, will work in the application of the patch to the process.

**Comment by joachimweyl** [comment]
Sounds like this is blocked once again as the fix that XDMoD provided did not work. @rob-baron has XDMoD provided any additional suggestions?

**Comment by rob-baron** [comment]
I am suspecting that this is either a caching problem or a configuration problem.  Will test more as I am testing the installation and will add to the ticket with the xdmod folks when I find out more.
