### ISSUE TITLE
Develop manifests and script to deploy xdmod on kubernetes

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/xdmod-cntr#23]
This Issue is to work on automating the yaml that was already created in #9 
As well as refine the containers and yaml so that they are more compact.
All necessary manifests are created.
DoD: With a list of commands deploy is automatic

**Comment by joachimweyl** [comment]
@rob-baron when you get a chance please define further what is meant by refining the containers and yaml, so that it is easily measured and completed.

**Comment by rob-baron** [comment]
see https://github.com/CCI-MOC/xdmod-cntr/pull/20.

**Comment by joachimweyl** [comment]
@rob-baron I still see 3 comments on the PR that are not yet resolved, are we ready to pull the PR once those 3 items are resolved?

**Comment by joachimweyl** [comment]
@rob-baron is this the code that you are testing on `ocp-staging`?

**Comment by joachimweyl** [comment]
@rob-baron according to your standup notes it sounds like this is resolved?

**Comment by rob-baron** [comment]
In my mind this is done, however, the yaml will still need to be changed/augmented for different systems.

**Comment by joachimweyl** [comment]
@rob-baron If the installer is ready for the system that we will be installing on, I would say that we can close this Issue and open a new one if/when we need to install on different systems. Thoughts?

**Comment by rob-baron** [comment]
Sure we can close this if it is the appropriate thing to do.
