### ISSUE TITLE
modify the data that is being placed in the compute event of the xdmod-openshift script as implied by shredding the data downstream of the aforementioned script.

### ISSUE THREAD

**Issue by rob-baron** [CCI-MOC/xdmod-cntr#24]
modify the data that is being placed in the compute event of the xdmod-openshift script as implied by shredding the data downstream of the aforementioned script.

**Comment by joachimweyl** [comment]
@rob-baron
1. What is the definition of done for this issue?
1. What issue will this solve?
1. How much work is left on this?

**Comment by rob-baron** [comment]
Come to think of it, this is badly worded.  What I am referring to were several issues with the data was being shredded, but not ingested.  It turned out to be less of a problem than anticipated - one I figured out which fields were causing the ingestion issue.

I consider this done.
