### ISSUE TITLE
Explore ways around the xdmod-shredding script failing due to the mariadb connection dropping.

### ISSUE THREAD

**Issue by rob-baron** [CCI-MOC/xdmod-cntr#25]
Explore ways around the xdmod-shredding script failing due to the mariadb connection dropping.

**Comment by larsks** [comment]
How is the shredding run right now -- via a Kubernetes job? Or some other mechanism?

**Comment by joachimweyl** [comment]
done

**Comment by rob-baron** [comment]
Larsks, 

Right now, it is done manually, in the container that has xdmod installed on it.

In their production it is to be run once a day, in a cron job.

Basically, 150K records seems to be too much for the job.  5K can get processed easily (without the job failing).
