### ISSUE TITLE
Collecting data from the nerc-openstack

### ISSUE THREAD

**Issue by rob-baron** [CCI-MOC/xdmod-cntr#26]
As the nerc-opnstack is running a newer version of openstack than what is currently on the MOC, it was felt that we should develop against this version of openstack as well.  I am adding this ticket as there are unexpected problems.

Configuration issues:

1) There was a networking issue which was quickly resolved
2) There seems to be a permissions issue that needs to be resolved

definition of done:  Connecting to and collecting some data from the nerc-openstack.

**Comment by joachimweyl** [comment]
@rob-baron 
1. How much work is left on this, it sounds like it is mostly done?

**Comment by rob-baron** [comment]
It is mostly done.  I have adjusted the setup process to handle the conversion of how kristi is using the application credentials to log into multiple OpenStack clusters to how I planned to do it.

I am using the same method to collect data from xdmod-openstack-hypervisor as I am from xdmod-openstack-reporting.

I do consider it done, though it doesn't address all of your concerns about potential differences in data between the version we are running in the MOC and on the NERC.  This won't be found until we actually start collecting and processing that data (starting later today).

**Comment by joachimweyl** [comment]
@rob-baron the title of this Issue is quite broad, can we narrow that down to something easier to define as done? While we are at it can we add a definition of done? For now, I would say it might be helpful to narrow this down to the point where it is done and close it. Then we can create a new Issue if there are any problems with collecting and processing the data.

**Comment by rob-baron** [comment]
Although this doesn't address all of your concerns for collection of data on the nerc, In order to limit this to a actionable issue, it is done as I was able to collect the hypervisor data from the nerc.
