### ISSUE TITLE
XDMod data for script update

### ISSUE THREAD

**Issue by rob-baron** [CCI-MOC/xdmod-cntr#3]
Ultimately, where and how should the data be collected.  

1. Current state of the xdmod-openshift-scrips - they don't work with the current version of OpenStack for 2 reasons:

    1.1. The Keystone API version they use is no longer shipped with OpenStack
    1.2. Panko/ceilometer are no longer being shipped with OpenStack
    1.3. It is polling once day
        1.3.1. This is ok for the events as they are stored in a time series database
        1.3.2. This may loose some auditability as some changes may not be collected 

2. Modified scripts:

    2.1. updated keystone API to v3  (https://github.com/CCI-MOC/xdmod-cntr/issues/2)
    2.2. use standard APIs to collect the event data  (https://github.com/CCI-MOC/xdmod-cntr/issues/2)
    2.3. changing the polling time to every 10 or 15 minutes  (https://github.com/CCI-MOC/xdmod-cntr/issues/15)
        2.3.1 Improves auditability  (nothing to do here)
        2.3.2 downside is collecting the same information multiple times.  (nothing to do here)

3. Future directions
      
    3.1.  What is our source of truth
        3.1.1 OpenStack
        3.1.2 STF
        3.1.3 ???

    3.2.  Use a queue to collect the event information
        3.2.1 relies on monitoring service to post event and information to the queue
        3.2.2 would remove the polling, simplifying data collection
        3.2.3. other information can be passed in to the queue, such as project hierarchy info.

The difference from where xdmod-openshift scripts collect the data from originally and where it is collecting it from currently.

Currently, the xdmod-openshift scripts uses an older keystone api version to authenticate which is no longer supported.  Additionally, one accesses internal databases of the panko and/or ceilometer databases to get event data.

Updating the keystone api version is required as the older keystone api version is no longer included in Openstack.

Rewriting the script that pulls data directly from panko/ceilometer is necessary as these services are not currently being shipped with OpenStack.  It appears that I can get the data from the nova client, though eventually, this should probably be reworked to become event driven from monitoring pushing events (and related data) into a queue to be processed by xdmod.

**Comment by joachimweyl** [comment]
This is now tracked via the milestone [XDMod Data for script update](https://github.com/CCI-MOC/xdmod-cntr/milestone/1)
