### ISSUE TITLE
Make the Openstack to xdmod files smaller so that shredding and ingestion can complete

### ISSUE THREAD

**Issue by rob-baron** [CCI-MOC/xdmod-cntr#31]
for the first run, we need to create a set of smaller files so that they will all be processed in a more timely manner than one large file.

**Comment by joachimweyl** [comment]
@rob-baron I updated the title for this Issue, please confirm this properly represents the work being done in this issue.

**Comment by joachimweyl** [comment]
@rob-baron I belive this has been done?

**Comment by rob-baron** [comment]
This development of this has been completed, it attached to a PR.   To accomplish this, I have separated the events into different files that occur on the same date.  That effectively breaks up one large file with ~2 years worth of transactions into ~700+ files, each with a set of daily transactions.  

The problem with the large file is that it takes too long to process.

This is attached to a PR that is still in draft.

To explain further:

Currently it is a draft PR as I have been unable to reproducibly have data appear in the interface after processing the files.

I have sent a small example of the data I am trying to import to the xdmod.  I have sent this example to the xdmod team and we are waiting for them to explain what needs to change in order that it can be imported.
