### ISSUE TITLE
piecewise generate the openstack reporting file.

### ISSUE THREAD

**Issue by rob-baron** [CCI-MOC/xdmod-cntr#32]
Need to be able to add to the current file while only adding existence events once an hour.  

The simplest implementation is to emit an existence even after any event that is not an existence event or to emit an existence event 1 hour past the previous existence event.  This simplifies the logic as we only need to keep track of the last event.

**Comment by joachimweyl** [comment]
@rob-baron is this currently part of PR20?

**Comment by rob-baron** [comment]
Not yet, this is something that I am currently working on, but should be done fairly soon.

Basically, we collect event data every 5 minutes.  We need to add in existents events at a rage of 1 per hour in order that we have smaller files  (why add 288 events per active VM per day (12 per hour * 24 hours) when 24 or, possibly, fewer will do).
