### ISSUE TITLE
xdmod possibly displays cloud by domain incorrectly

### ISSUE THREAD

**Issue by rob-baron** [CCI-MOC/xdmod-cntr#34]
For example, with 2 different resources which both have the same domain, xdmod combines those 2 domains.

The 2 different resources would be the test data (from the resource file) and the data from kaizen, so I could see separating the openstack default domain being separate domains.

Not sure if we should separate all domains, but I have the feeling that we should probably figure out how to do this.

**Comment by joachimweyl** [comment]
We need to ask Scott & Wayne. We will ask this in our Wed meeting tomorrow.

**Comment by rob-baron** [comment]
Possible questions (for domains and projects)

For a domain like "default" which is going to be the same on all OpenStack installations as it is a default domain, I feel that it should be considered different for each OpenStack instance.    But for other domains share the same name between clusters  I am less certain, as I can come up with arguments for either.

Also, should projects be aggregated across different resources (openstack, openshift ... )?  or would this be more of a project by project decision?

**Comment by joachimweyl** [comment]
This is not how XDMoD is created. We will create an Issue to track how we plan to resolve this in our instance.
