### ISSUE TITLE
stop using /root as the data directory

### ISSUE THREAD

**Issue by rob-baron** [CCI-MOC/xdmod-cntr#36]
Create mount the pv that stores the data files at /data

**Comment by rob-baron** [comment]
This is something that is just going to happen over a number of seemingly unrelated PRs.  In fact it has begun and you haven't realized it.  For example, for new work, we are doing things from either /mnt or from a new directory /data.  this way we don't use the "special" directory /root.

You seem to really want this done, however, I feel that this is a lower priority than say the volume data, or the creation of the job to collect and shred the data coming from OpenStack.  When I create that PR to collect and shred the data coming from OpenStack, this will mostly be done by that PR as I will be loading the new data to be shredded into a "/data" directory as opposed to using "/root"

**Comment by joachimweyl** [comment]
@rob-baron this is not a priority unless it is blocking the installation which I don't believe it is. It sounds like it is being solved in pieces which is fine. Thank you for detailing how and where this will be done.
