### ISSUE TITLE
Unable to load metric explorer

### ISSUE THREAD

**Issue by rob-baron** [CCI-MOC/xdmod-cntr#40]
After logging in, when I select the metric explorer, I get a message box that states that 'cloud' is an unknown realm, and the page fails to load.  Have submitted a ticket to the xdmod team concerning this with the relevant screen shots and (hopefully) the relevant log file.

**Comment by rob-baron** [comment]
xdmod team asked if I was able to connect to mariadb with the username/password in the portal_settings.ini file.

Gave an example demonstrating that I was able to.  Also explained that we were having a intermittent problem with the database dropping the connection.

Waiting for a reply.

**Comment by joachimweyl** [comment]
@rob-baron has XDMoD responded?

**Comment by rob-baron** [comment]
still waiting for the reply, unfortunately, I suspect that they will require an example that reproduces the problem.

**Comment by joachimweyl** [comment]
Blocked on XDMoD response testing.
