### ISSUE TITLE
share configuration files though the database.

### ISSUE THREAD

**Issue by rob-baron** [CCI-MOC/xdmod-cntr#44]
Since there are no plans to support RWX permissions on OpenShift and it is straightforward to store text files (that are small) in the database, we can write the configuration file when we produce it during xdmod-setup, then read it from the database when we need it.

**Comment by joachimweyl** [comment]
@rob-baron I associated this with PR51 which is now merged. Was that the correct PR to link it to and if so does that mean this issue is resolved?

**Comment by joachimweyl** [comment]
Closing as https://github.com/CCI-MOC/xdmod-cntr/pull/51 is done
