### ISSUE TITLE
define a kubernetes cron job to run the collection/shredding/

### ISSUE THREAD

**Issue by rob-baron** [CCI-MOC/xdmod-cntr#46]
Use a kubernetes cron job to run the data collection/shredding 

this is dependent on uploading and downloading of config files as the nerc openshift doesn't yet support RWX.

**Comment by rob-baron** [comment]
Am able to download the configuration data from the database - kludge to work-a-round the lack of RWX volumes on our OpenShift cluster.

Found that centos7 was not loading python3 in a useable form.  Decided to redo the data collection routine in the python 3.9 container and run as an init container for this container.

**Comment by rob-baron** [comment]
This is blocked on ( )/(https://github.com/CCI-MOC/xdmod-cntr/issues/117) 

Can't test this part until it is able to connect to the OpenStack cluster.

**Comment by joachimweyl** [comment]
@rob-baron #117 is resolved.
Is this cron job still blocked on OCP-on-NERC/operations#64

**Comment by rob-baron** [comment]
@joachimweyl This was blocked before the rebuilds of the infra cluster on https://github.com/OCP-on-NERC/operations/issues/64 and was blocked when I went on PTO on the same issue, after I had to compensate for the changes that the rebuilds made.

**Comment by joachimweyl** [comment]
@rob-baron just to confirm, does this mean we are no longer blocked?

**Comment by rob-baron** [comment]
@joachimweyl This project is blocked by https://github.com/OCP-on-NERC/operations/issues/64

Sorry, I gave you too many details, as I fixed the issues that cropped up due to how nerc-ocp-infra changed during the rebuilds.

**Comment by rob-baron** [comment]
And I have confirmed that I am still blocked with:
```
oc --as system:admin rsh xdmod-ui-7f8d4d457b-jhlpc
Defaulted container "xdmod" out of: xdmod, xdmod-init-1 (init), xdmod-init-2 (init)
sh-4.2$ curl https://stack.nerc.mghpcc.org:13000 
curl: (7) Failed connect to stack.nerc.mghpcc.org:13000; Connection timed out
sh-4.2$ % 
```

**Comment by joachimweyl** [comment]
The cron job is running to completion!
