### ISSUE TITLE
define a kubernetes cron job to run the ingestion of xdmod data

### ISSUE THREAD

**Issue by rob-baron** [CCI-MOC/xdmod-cntr#49]
This is to define a job to run the ingestion process to get data that has been shredded can be made available for xdmod to display

**Comment by joachimweyl** [comment]
@rob-baron I see this is In review but I do not see a PR associated with it. Can we please add the PR in the "Development" section of GitHub?

**Comment by joachimweyl** [comment]
@rob-baron I am reviewing the Agenda from last week's Wed NERC meeting and you said you felt like Data ingestion would be ready for next week's meeting which is tomorrow. Do you still expect this issue to be resolved by tomorrow?

**Comment by joachimweyl** [comment]
closing due to PR https://github.com/CCI-MOC/xdmod-cntr/pull/52 done.
