### ISSUE TITLE
Install the NERC xdmod 

### ISSUE THREAD

**Issue by rob-baron** [CCI-MOC/xdmod-cntr#57]
Install the xdmod UI onto the infra openshift cluster for the NERC.

This will be done via a PR to https://github.com/OCP-on-NERC/nerc-ocp-apps

**Comment by joachimweyl** [comment]
As the PR is in a different Repo I will link the PR [here](https://github.com/OCP-on-NERC/nerc-ocp-apps/pull/6).

**Comment by joachimweyl** [comment]
@rob-baron great work on getting those 4 PR's in. How goes the NERC install now that those are all merged?

**Comment by joachimweyl** [comment]
@rob-baron ^

**Comment by joachimweyl** [comment]
Installed.
