### ISSUE TITLE
perform benchmarks on mariadb in staging

### ISSUE THREAD

**Issue by rob-baron** [CCI-MOC/xdmod-cntr#62]
I have the feeling that mariadb is not performing operations as quickly as I would expect.  Not sure where the problem lies.

Will look around for a database performance suite to run in order to gain more insight in to our connection issue that we are seeing in staging and on the nerc.

**Comment by msdisme** [comment]
Moved to blocked by create a reproducer since that is higher priority/and how you plan to do the testing.

**Comment by joachimweyl** [comment]
complete.
