### ISSUE TITLE
Possibility for AttributeError in moc_openstack_api_reporting.py

### ISSUE THREAD

**Issue by larsks** [CCI-MOC/xdmod-cntr#66]
In `moc_openstack_api_reporting.py`, in line 227 (as of 6abefac), we see:

```
    vm_volumes = getattr(server, "os-extended-volumes:volumes_attached", [])
    for vol in vm_volumes.values():
```

There is a problem here: we're calling `vm_volumes.values()`, so we expect `vm_volumes` to be a dictionary, but `getattr` returns a list (`[]`) as the default value. This needs to be:

```
    vm_volumes = getattr(server, "os-extended-volumes:volumes_attached", {})
    for vol in vm_volumes.values():
```

**Comment by rob-baron** [comment]
This is in a function that I was using, but am no longer use.  was waiting to get the volume events a bit more developed before I either fix or delete this function
