### ISSUE TITLE
Reverse Engineered ER diagrams for all of the databases used by XDMod.

### ISSUE THREAD

**Issue by rob-baron** [CCI-MOC/xdmod-cntr#7]
Created ER diagrams based on the what is present.  These are living documents - not sure where to store them.

**Comment by joachimweyl** [comment]
will be added to the repo

**Comment by joachimweyl** [comment]
Worth asking if they have this and if not providing it to them.

**Comment by joachimweyl** [comment]
@rob-baron was this added to the repo? If so let's link it here and close the ticket.
How much extra work would it be to add to the XDMoD project so others can benefit?

**Comment by rob-baron** [comment]
For an initial swipe, it doesn't require much effort, so I will redo them for xdmod v10
