### ISSUE TITLE
updating the xdmod-openshift-report script to incorporate changes suggested by the xdmod group, specifically, using the openstack specific structures

### ISSUE THREAD

**Issue by rob-baron** [CCI-MOC/xdmod-cntr#8]
suggestion was to use openstack specific structures as opposed to the general structure specified in the xdmod docs.

This requires analysis of the events as reported by ceilometer and map those to the events that I are currently reported by openstack. 

- [x] #10
- [ ] #11
- [ ] #12
- [ ] #13

**Comment by joachimweyl** [comment]
closing issue since all of its parts are now part of other issues.

**Comment by joachimweyl** [comment]
As this issue has had all of its parts broken into other issues, this is now being tracked by the Milestone and no longer requires this ticket to track it.
