### ISSUE TITLE
Ingestion error, Data too long for field

### ISSUE THREAD

**Issue by rob-baron** [CCI-MOC/xdmod-cntr#80]
While working though the xdmod-ingestor output, came across:

2022-09-22 17:51:10 [error] {"message":"xdmod.jobs-cloud-extract-openstack.OpenStackCloudStagingEventIngestor (ETL\\Ingestor\\DatabaseIngestor): SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'user_name' at row 179 Exception: 'SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'user_name' at row 179'"}

**Comment by rob-baron** [comment]
greping from the sql that defines the databases, yeild:

Rob@Roberts-Computer sql % grep user_name *.sql
mod_shredder.sql:  `user_name` varchar(255) NOT NULL,
mod_shredder.sql:  KEY `user_name` (`user_name`,`resource_name`,`pi_name`)
mod_shredder.sql:  `user_name` varchar(255) NOT NULL,
mod_shredder.sql:  `user_name` tinytext NOT NULL,
mod_shredder.sql:  `user_name` varchar(255) NOT NULL,
mod_shredder.sql:  `user_name` varchar(255) NOT NULL COMMENT 'User''s system username',
mod_shredder.sql:  UNIQUE KEY `uk_usage` (`resource_name`,`mountpoint_name`,`user_name`,`pi_name`,`dt`),
mod_shredder.sql:  KEY `idx_user_name` (`user_name`),
mod_shredder.sql:  KEY `idx_resource_name_pi_name_user_name` (`resource_name`,`pi_name`,`user_name`),
mod_shredder.sql:  KEY `idx_resource_name_user_name` (`resource_name`,`user_name`)
mod_shredder.sql:  `user_name` varchar(255) NOT NULL COMMENT 'User username',
mod_shredder.sql:  PRIMARY KEY (`user_name`,`pi_name`,`resource_name`),
modw_cloud.sql:  `user_name` varchar(32) DEFAULT NULL COMMENT 'Username associated with event',
modw_cloud.sql:  `user_name` varchar(255) DEFAULT NULL,
modw_cloud.sql:  `user_name` varchar(32) DEFAULT NULL COMMENT 'Username associated with event',

what sticks out is that user_name is defined by multiple types:

        varchar(255)
        varchar(32)
        tinytext              - this is actually 255 characters long
        
I suspect the error is due to truncating a 255 character varchar/tinytext to a varchar(32).

**Comment by rob-baron** [comment]
The xdmod-ingestor process will update the database structure to how it is defined in a set of JSON files located under (configuration/etl/etl_tables.d).  There is a list of logical databases as the directory names (cloud_generic, cloud_openstack and cloud_common are combined to form modw_cloud).  Within this directory are JSON files that define the tables.  For example  cloud_openstack % cat raw_event.json will produce the table definition for modw_cloud.openstack_raw_event.

**Comment by joachimweyl** [comment]
resolved.

**Comment by rob-baron** [comment]
Just to define what kim means my locally, xdmod developer gregory dean will be updating the main repository.
