### ISSUE TITLE
A useable xdmod instance with the NERC data housed on NERC Infra

### ISSUE THREAD

**Issue by rob-baron** [CCI-MOC/xdmod-cntr#85]
Until we get a fully operation instance up on the nerc, this issue is meant to present to the team a useable instance of xdmod in order to determine practical problems that need to be solved.
We have the NERC data on MOC staging.
The next step is to house the NERC data on the NERC Infra.

**Comment by rob-baron** [comment]
Here is the link for xdmod running on ocp-staging:

http://xdmod-xdmod.apps.ocp-staging.massopen.cloud/).

**Comment by rob-baron** [comment]
Instead of using a timestamp to keep track of the daily totals, or generating a new daily record each day, they initialize the daily table with a set of days (up to ~2038).  This  gives each day an id.  This process is suppose to run to completion during the xdmod-setup phase - unfortunately it stopped in the middle.

So greg had me run the following php script:

```
<?php


namespace OpenXdmod\Setup;

require __DIR__ . '/../../configuration/linker.php';

use CCR\Log;
use TimePeriodGenerator;
use CCR\DB\MySQLHelper;
use CCR\DB;
use ETL\Utilities;

$aggregationUnits = array(
    'day',
    'month',
    'quarter',
    'year'
);

foreach ($aggregationUnits as $aggUnit) {
    $tpg = TimePeriodGenerator::getGeneratorForUnit($aggUnit);
    $tpg->generateMainTable(DB::factory('datawarehouse'), new \DateTime('2000-01-01'), new \DateTime('2038-01-18'));
}             
```

Which initialized the tables.

Data has appeared in the UI, so we now have a usable xdmod instance in the NERC.

**Comment by joachimweyl** [comment]
@rob-baron now that this is closed I assume this means that http://xdmod-xdmod.apps.nerc-ocp-infra.rc.fas.harvard.edu/ is live and ready for @waygil & @syockel to review?

**Comment by rob-baron** [comment]
@joachimweyl The xdmod-ui is up on the nerc with some data from the nerc.

Currently working on getting the job to run.
