### ISSUE TITLE
write yaml to deploy xdmod on kubernetes.

### ISSUE THREAD

**Issue by rob-baron** [CCI-MOC/xdmod-cntr#9]
Create the yaml to deploy xdmod on kubernetes/openshift.

**Comment by joachimweyl** [comment]
@rob-baron It sounds like you have a yaml to deploy XDMoD on Kubernetes, am I correct that you are done with this issue?

**Comment by rob-baron** [comment]
It is basically done, I am just working on eliminating the manual processes and refine the containers/yaml.

**Comment by rob-baron** [comment]
ok, I'll go with 2.  But my brain is elsewhere at the moment

**Comment by joachimweyl** [comment]
@rob-baron totally understands, focus on the compute data, I will break this out and close it.

**Comment by joachimweyl** [comment]
yaml is in working condition. It takes about 30 min and requires some manual steps.
