### ISSUE TITLE
xdmod-openshift-prod-job failing due to old image

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/xdmod-cntr#94]
@rob-baron Hi! I triggered a run of the xdmod-openshift-prod-job, and it's currently trying to pull the metric "kube_pod_init_container_resource_requests_cpu_cores". This doesn't exist in the prod server; the xdmod-openshift-scripts repository was updated to grab a different metric. Can we rebuild the xdmod images?

**Comment by rob-baron** [comment]
This was solved by using a PR removing the patches.  The build was performed automatically on the nerc.
